-- FanGraphs Complete Schema (Corrected to match ETL output)

-- ============================================================================
-- FANGRAPHS BATTING LEADERS (Exact column match)
-- ============================================================================

CREATE TABLE IF NOT EXISTS fg_batting_raw (
    -- Core identifiers
    season INTEGER,
    team_name VARCHAR(100),
    bats VARCHAR(5),
    xmlbamid INTEGER,
    playernameroute VARCHAR(255),
    playername VARCHAR(255),
    playerid INTEGER,
    age INTEGER,
    agerng VARCHAR(10),
    seasonmin INTEGER,
    seasonmax INTEGER,
    
    -- Basic stats
    g INTEGER,
    ab INTEGER,
    pa INTEGER,
    h INTEGER,
    singles INTEGER,
    doubles INTEGER,
    triples INTEGER,
    hr INTEGER,
    r INTEGER,
    rbi INTEGER,
    bb INTEGER,
    so INTEGER,
    sb INTEGER,
    cs INTEGER,
    
    -- Rate stats
    batting_avg NUMERIC(6,3),
    bb_pct NUMERIC(6,2),
    k_pct NUMERIC(6,2),
    bb_k NUMERIC(6,3),
    obp NUMERIC(6,3),
    slg NUMERIC(6,3),
    ops NUMERIC(6,3),
    iso NUMERIC(6,3),
    babip NUMERIC(6,3),
    tto_pct NUMERIC(6,2),
    
    -- Advanced metrics
    woba NUMERIC(6,3),
    wraa NUMERIC(8,1),
    wrc INTEGER,
    batting NUMERIC(8,1),
    fielding NUMERIC(8,1),
    replacement NUMERIC(8,1),
    positional NUMERIC(8,1),
    wleague NUMERIC(8,1),
    defense NUMERIC(8,1),
    offense NUMERIC(8,1),
    rar NUMERIC(8,1),
    war NUMERIC(6,1),
    warold NUMERIC(6,1),
    baserunning NUMERIC(8,1),
    spd NUMERIC(6,1),
    wrc_plus INTEGER,
    wbsr NUMERIC(8,1),
    
    -- Team value stats
    rfteamv NUMERIC(8,1),
    rbteamv NUMERIC(8,1),
    rtv NUMERIC(8,1),
    events INTEGER,
    q NUMERIC(6,1),
    tg INTEGER,
    tpa INTEGER,
    pos VARCHAR(10),
    team_name_abb VARCHAR(10),
    teamid INTEGER,
    pos_num NUMERIC(6,1),
    
    -- Additional counting stats
    hbp INTEGER,
    sh INTEGER,
    gdp INTEGER,
    ibb INTEGER,
    sf INTEGER,
    
    -- Win probability
    wpa NUMERIC(8,2),
    wpa_minus NUMERIC(8,2),
    wpa_plus NUMERIC(8,2),
    re24 NUMERIC(8,1),
    rew NUMERIC(8,1),
    pli NUMERIC(6,2),
    ph INTEGER,
    wpa_li NUMERIC(8,2),
    clutch NUMERIC(8,2),
    phli NUMERIC(6,2),
    
    -- Batted ball data
    gb INTEGER,
    fb INTEGER,
    ld INTEGER,
    iffb INTEGER,
    pitches INTEGER,
    balls INTEGER,
    strikes INTEGER,
    ifh INTEGER,
    bu INTEGER,
    buh INTEGER,
    gb_fb NUMERIC(6,3),
    ld_pct NUMERIC(6,2),
    gb_pct NUMERIC(6,2),
    fb_pct NUMERIC(6,2),
    iffb_pct NUMERIC(6,2),
    hr_fb NUMERIC(6,2),
    ifh_pct NUMERIC(6,2),
    buh_pct NUMERIC(6,2),
    dollars NUMERIC(10,1),
    
    -- Pitch type percentages (fb_pct1 = fastball %)
    fb_pct1 NUMERIC(6,2),
    fbv NUMERIC(6,1),
    sl_pct NUMERIC(6,2),
    slv NUMERIC(6,1),
    cb_pct NUMERIC(6,2),
    cbv NUMERIC(6,1),
    ch_pct NUMERIC(6,2),
    chv NUMERIC(6,1),
    sf_pct NUMERIC(6,2),
    sfv NUMERIC(6,1),
    xx_pct NUMERIC(6,2),
    
    -- Pitch values
    wfb NUMERIC(8,1),
    wsl NUMERIC(8,1),
    wcb NUMERIC(8,1),
    wch NUMERIC(8,1),
    wsf NUMERIC(8,1),
    wfb_c NUMERIC(8,1),
    wsl_c NUMERIC(8,1),
    wcb_c NUMERIC(8,1),
    wch_c NUMERIC(8,1),
    wsf_c NUMERIC(8,1),
    
    -- Plate discipline
    o_swing_pct NUMERIC(6,2),
    z_swing_pct NUMERIC(6,2),
    swing_pct NUMERIC(6,2),
    o_contact_pct NUMERIC(6,2),
    z_contact_pct NUMERIC(6,2),
    contact_pct NUMERIC(6,2),
    zone_pct NUMERIC(6,2),
    f_strike_pct NUMERIC(6,2),
    swstr_pct NUMERIC(6,2),
    cstr_pct NUMERIC(6,2),
    c_swstr_pct NUMERIC(6,2),
    
    -- Batted ball direction
    pull INTEGER,
    cent INTEGER,
    oppo INTEGER,
    soft INTEGER,
    med INTEGER,
    hard INTEGER,
    bipcount INTEGER,
    pull_pct NUMERIC(6,2),
    cent_pct NUMERIC(6,2),
    oppo_pct NUMERIC(6,2),
    soft_pct NUMERIC(6,2),
    med_pct NUMERIC(6,2),
    hard_pct NUMERIC(6,2),
    
    -- Baserunning
    ubr NUMERIC(8,1),
    gdpruns NUMERIC(8,1),
    
    -- Duplicate columns (different calculations)
    ld_pct2 NUMERIC(6,2),
    gb_pct2 NUMERIC(6,2),
    fb_pct2 NUMERIC(6,2),
    hrfb_pct NUMERIC(6,2),
    pull_pct2 NUMERIC(6,2),
    cent_pct2 NUMERIC(6,2),
    oppo_pct2 NUMERIC(6,2),
    soft_pct2 NUMERIC(6,2),
    med_pct2 NUMERIC(6,2),
    hard_pct2 NUMERIC(6,2),
    
    -- Knuckleball
    kn_pct NUMERIC(6,2),
    knv NUMERIC(6,1),
    wkn NUMERIC(8,1),
    wkn_c NUMERIC(8,1),
    
    -- Cutter/Sinker
    po_pct NUMERIC(6,2),
    ct_pct NUMERIC(6,2),
    ctv NUMERIC(6,1),
    wct NUMERIC(8,1),
    wct_c NUMERIC(8,1),
    dgv NUMERIC(8,1),
    
    -- PITCHf/x data
    pfx_fa_pct NUMERIC(6,2),
    pfx_fc_pct NUMERIC(6,2),
    pfx_fs_pct NUMERIC(6,2),
    pfx_si_pct NUMERIC(6,2),
    pfx_sl_pct NUMERIC(6,2),
    pfx_cu_pct NUMERIC(6,2),
    pfx_ch_pct NUMERIC(6,2),
    pfx_vfa NUMERIC(6,1),
    pfx_vfc NUMERIC(6,1),
    pfx_vfs NUMERIC(6,1),
    pfx_vsi NUMERIC(6,1),
    pfx_vsl NUMERIC(6,1),
    pfx_vcu NUMERIC(6,1),
    pfx_vch NUMERIC(6,1),
    pfx_fa_x NUMERIC(6,2),
    pfx_fc_x NUMERIC(6,2),
    pfx_fs_x NUMERIC(6,2),
    pfx_si_x NUMERIC(6,2),
    pfx_sl_x NUMERIC(6,2),
    pfx_cu_x NUMERIC(6,2),
    pfx_ch_x NUMERIC(6,2),
    pfx_fa_z NUMERIC(6,2),
    pfx_fc_z NUMERIC(6,2),
    pfx_fs_z NUMERIC(6,2),
    pfx_si_z NUMERIC(6,2),
    pfx_sl_z NUMERIC(6,2),
    pfx_cu_z NUMERIC(6,2),
    pfx_ch_z NUMERIC(6,2),
    pfx_wfa NUMERIC(8,1),
    pfx_wfc NUMERIC(8,1),
    pfx_wfs NUMERIC(8,1),
    pfx_wsi NUMERIC(8,1),
    pfx_wsl NUMERIC(8,1),
    pfx_wcu NUMERIC(8,1),
    pfx_wch NUMERIC(8,1),
    pfx_wfa_c NUMERIC(8,1),
    pfx_wfc_c NUMERIC(8,1),
    pfx_wfs_c NUMERIC(8,1),
    pfx_wsi_c NUMERIC(8,1),
    pfx_wsl_c NUMERIC(8,1),
    pfx_wcu_c NUMERIC(8,1),
    pfx_wch_c NUMERIC(8,1),
    pfx_o_swing_pct NUMERIC(6,2),
    pfx_z_swing_pct NUMERIC(6,2),
    pfx_swing_pct NUMERIC(6,2),
    pfx_o_contact_pct NUMERIC(6,2),
    pfx_z_contact_pct NUMERIC(6,2),
    pfx_contact_pct NUMERIC(6,2),
    pfx_zone_pct NUMERIC(6,2),
    
    -- PITCHInfo data
    pi_ch_pct NUMERIC(6,2),
    pi_cu_pct NUMERIC(6,2),
    pi_fa_pct NUMERIC(6,2),
    pi_fc_pct NUMERIC(6,2),
    pi_fs_pct NUMERIC(6,2),
    pi_si_pct NUMERIC(6,2),
    pi_sl_pct NUMERIC(6,2),
    pi_xx_pct NUMERIC(6,2),
    pi_vch NUMERIC(6,1),
    pi_vcu NUMERIC(6,1),
    pi_vfa NUMERIC(6,1),
    pi_vfc NUMERIC(6,1),
    pi_vfs NUMERIC(6,1),
    pi_vsi NUMERIC(6,1),
    pi_vsl NUMERIC(6,1),
    pi_vxx NUMERIC(6,1),
    pi_ch_x NUMERIC(6,2),
    pi_cu_x NUMERIC(6,2),
    pi_fa_x NUMERIC(6,2),
    pi_fc_x NUMERIC(6,2),
    pi_fs_x NUMERIC(6,2),
    pi_si_x NUMERIC(6,2),
    pi_sl_x NUMERIC(6,2),
    pi_xx_x NUMERIC(6,2),
    pi_ch_z NUMERIC(6,2),
    pi_cu_z NUMERIC(6,2),
    pi_fa_z NUMERIC(6,2),
    pi_fc_z NUMERIC(6,2),
    pi_fs_z NUMERIC(6,2),
    pi_si_z NUMERIC(6,2),
    pi_sl_z NUMERIC(6,2),
    pi_xx_z NUMERIC(6,2),
    pi_wch NUMERIC(8,1),
    pi_wcu NUMERIC(8,1),
    pi_wfa NUMERIC(8,1),
    pi_wfc NUMERIC(8,1),
    pi_wfs NUMERIC(8,1),
    pi_wsi NUMERIC(8,1),
    pi_wsl NUMERIC(8,1),
    pi_wxx NUMERIC(8,1),
    pi_wch_c NUMERIC(8,1),
    pi_wcu_c NUMERIC(8,1),
    pi_wfa_c NUMERIC(8,1),
    pi_wfc_c NUMERIC(8,1),
    pi_wfs_c NUMERIC(8,1),
    pi_wsi_c NUMERIC(8,1),
    pi_wsl_c NUMERIC(8,1),
    pi_wxx_c NUMERIC(8,1),
    pi_o_swing_pct NUMERIC(6,2),
    pi_z_swing_pct NUMERIC(6,2),
    pi_swing_pct NUMERIC(6,2),
    pi_o_contact_pct NUMERIC(6,2),
    pi_z_contact_pct NUMERIC(6,2),
    pi_contact_pct NUMERIC(6,2),
    pi_zone_pct NUMERIC(6,2),
    
    -- StatCast
    barrels INTEGER,
    hardhit INTEGER,
    
    -- Additional pitch types
    pi_kn_pct NUMERIC(6,2),
    pi_vkn NUMERIC(6,1),
    pi_kn_x NUMERIC(6,2),
    pi_kn_z NUMERIC(6,2),
    pi_wkn NUMERIC(8,1),
    pi_wkn_c NUMERIC(8,1),
    pfx_kn_pct NUMERIC(6,2),
    pfx_vkn NUMERIC(6,1),
    pfx_kn_x NUMERIC(6,2),
    pfx_kn_z NUMERIC(6,2),
    pfx_wkn NUMERIC(8,1),
    pfx_wkn_c NUMERIC(8,1),
    
    -- Stolen bases (pitcher perspective)
    pi_cs_pct NUMERIC(6,2),
    pi_sb_pct NUMERIC(6,2),
    pi_vcs NUMERIC(6,1),
    pi_vsb NUMERIC(6,1),
    pi_cs_x NUMERIC(6,2),
    pi_sb_x NUMERIC(6,2),
    pi_cs_z NUMERIC(6,2),
    pi_sb_z NUMERIC(6,2),
    pi_wcs NUMERIC(8,1),
    pi_wsb NUMERIC(8,1),
    pi_wcs_c NUMERIC(8,1),
    pi_wsb_c NUMERIC(8,1),
    
    -- More PITCHf/x
    pfx_kc_pct NUMERIC(6,2),
    pfx_vkc NUMERIC(6,1),
    pfx_kc_x NUMERIC(6,2),
    pfx_kc_z NUMERIC(6,2),
    pfx_wkc NUMERIC(8,1),
    pfx_wkc_c NUMERIC(8,1),
    
    -- Catcher framing
    cframing NUMERIC(8,1),
    
    -- More PITCHf/x pitch types
    pfx_ep_pct NUMERIC(6,2),
    pfx_vep NUMERIC(6,1),
    pfx_ep_x NUMERIC(6,2),
    pfx_ep_z NUMERIC(6,2),
    pfx_wep NUMERIC(8,1),
    pfx_wep_c NUMERIC(8,1),
    pfx_sc_pct NUMERIC(6,2),
    pfx_vsc NUMERIC(6,1),
    pfx_sc_x NUMERIC(6,2),
    pfx_sc_z NUMERIC(6,2),
    pfx_wsc NUMERIC(8,1),
    pfx_wsc_c NUMERIC(8,1),
    pfx_fo_pct NUMERIC(6,2),
    pfx_vfo NUMERIC(6,1),
    pfx_fo_x NUMERIC(6,2),
    pfx_fo_z NUMERIC(6,2),
    pfx_wfo NUMERIC(8,1),
    pfx_wfo_c NUMERIC(8,1),
    pfx_pace NUMERIC(6,2),
    pi_pace NUMERIC(6,2),
    
    -- Expected stats
    xwoba NUMERIC(6,3),
    xavg NUMERIC(6,3),
    xslg NUMERIC(6,3),
    
    -- StatCast metrics
    ev NUMERIC(6,1),
    la NUMERIC(6,1),
    barrel_pct NUMERIC(6,2),
    maxev NUMERIC(6,1),
    hardhit_pct NUMERIC(6,2),
    ev90 NUMERIC(6,1),
    xbr NUMERIC(8,1),
    
    -- Team value metrics
    pptv NUMERIC(8,1),
    cptv NUMERIC(8,1),
    bptv NUMERIC(8,1),
    dsv NUMERIC(8,1),
    btv NUMERIC(8,1),
    rpptv NUMERIC(8,1),
    rbptv NUMERIC(8,1),
    ebv NUMERIC(8,1),
    esv NUMERIC(8,1),
    rbtv NUMERIC(8,1),
    rcptv NUMERIC(8,1),
    rdgv NUMERIC(8,1),
    rdsv NUMERIC(8,1),
    
    -- Import metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (playerid, season)
);

-- ============================================================================
-- FANGRAPHS PITCHING LEADERS (Exact column match)
-- ============================================================================

CREATE TABLE IF NOT EXISTS fg_pitching_raw (
    -- Core identifiers
    season INTEGER,
    team_name VARCHAR(100),
    throws VARCHAR(5),
    xmlbamid INTEGER,
    playernameroute VARCHAR(255),
    playername VARCHAR(255),
    playerid INTEGER,
    age INTEGER,
    agerng VARCHAR(10),
    seasonmin INTEGER,
    seasonmax INTEGER,
    
    -- Basic pitching stats
    w INTEGER,
    l INTEGER,
    era NUMERIC(6,2),
    g INTEGER,
    gs INTEGER,
    cg INTEGER,
    sho INTEGER,
    sv INTEGER,
    ip NUMERIC(8,1),
    h INTEGER,
    r INTEGER,
    er INTEGER,
    hr INTEGER,
    bb INTEGER,
    bk INTEGER,
    so INTEGER,
    k_9 NUMERIC(6,2),
    bb_9 NUMERIC(6,2),
    k_bb NUMERIC(6,3),
    h_9 NUMERIC(6,2),
    hr_9 NUMERIC(6,2),
    batting_avg NUMERIC(6,3),
    whip NUMERIC(6,3),
    babip NUMERIC(6,3),
    lob_pct NUMERIC(6,2),
    fip NUMERIC(6,2),
    
    -- Advanced metrics
    rar NUMERIC(8,1),
    war NUMERIC(6,1),
    ra9_wins NUMERIC(6,1),
    lob_wins NUMERIC(6,1),
    bip_wins NUMERIC(6,1),
    bs_wins NUMERIC(6,1),
    games NUMERIC(6,1),
    era2 NUMERIC(6,2),
    fip2 NUMERIC(6,2),
    kwera NUMERIC(6,2),
    e_f NUMERIC(6,2),
    k_92 NUMERIC(6,2),
    bb_92 NUMERIC(6,2),
    k_bb2 NUMERIC(6,3),
    h_92 NUMERIC(6,2),
    hr_92 NUMERIC(6,2),
    batting_avg2 NUMERIC(6,3),
    whip2 NUMERIC(6,3),
    babip2 NUMERIC(6,3),
    lob_pct2 NUMERIC(6,2),
    
    -- Team value
    rfteamv NUMERIC(8,1),
    rbteamv NUMERIC(8,1),
    rtv NUMERIC(8,1),
    events INTEGER,
    q NUMERIC(6,1),
    tg INTEGER,
    tip NUMERIC(8,1),
    pos VARCHAR(10),
    team_name_abb VARCHAR(10),
    teamid INTEGER,
    
    -- Additional counting stats
    wp INTEGER,
    hbp INTEGER,
    tbf INTEGER,
    tto_pct NUMERIC(6,2),
    k_pct NUMERIC(6,2),
    bb_pct NUMERIC(6,2),
    k_bb_pct NUMERIC(6,2),
    k_pct2 NUMERIC(6,2),
    bb_pct2 NUMERIC(6,2),
    ibb INTEGER,
    qs INTEGER,
    
    -- Role splits
    starting NUMERIC(6,1),
    start_ip NUMERIC(8,1),
    
    -- Win probability
    wpa NUMERIC(8,2),
    wpa_minus NUMERIC(8,2),
    wpa_plus NUMERIC(8,2),
    re24 NUMERIC(8,1),
    rew NUMERIC(8,1),
    pli NUMERIC(6,2),
    inli NUMERIC(6,2),
    gmli NUMERIC(6,2),
    exli NUMERIC(6,2),
    pulls NUMERIC(6,2),
    wpa_li NUMERIC(8,2),
    clutch NUMERIC(8,2),
    sd INTEGER,
    md INTEGER,
    
    -- Relief stats
    relieving NUMERIC(6,1),
    relief_ip NUMERIC(8,1),
    bs INTEGER,
    
    -- Batted ball data
    gb INTEGER,
    fb INTEGER,
    ld INTEGER,
    iffb INTEGER,
    pitches INTEGER,
    balls INTEGER,
    strikes INTEGER,
    rs INTEGER,
    ifh INTEGER,
    bu INTEGER,
    buh INTEGER,
    gb_fb NUMERIC(6,3),
    ld_pct NUMERIC(6,2),
    gb_pct NUMERIC(6,2),
    fb_pct NUMERIC(6,2),
    iffb_pct NUMERIC(6,2),
    hr_fb NUMERIC(6,2),
    ifh_pct NUMERIC(6,2),
    buh_pct NUMERIC(6,2),
    dollars NUMERIC(10,1),
    tera NUMERIC(6,2),
    xfip NUMERIC(6,2),
    
    -- Pitch type percentages
    fb_pct1 NUMERIC(6,2),
    fbv NUMERIC(6,1),
    sl_pct NUMERIC(6,2),
    slv NUMERIC(6,1),
    cb_pct NUMERIC(6,2),
    cbv NUMERIC(6,1),
    ch_pct NUMERIC(6,2),
    chv NUMERIC(6,1),
    sf_pct NUMERIC(6,2),
    sfv NUMERIC(6,1),
    xx_pct NUMERIC(6,2),
    
    -- Pitch values
    wfb NUMERIC(8,1),
    wsl NUMERIC(8,1),
    wcb NUMERIC(8,1),
    wch NUMERIC(8,1),
    wsf NUMERIC(8,1),
    wfb_c NUMERIC(8,1),
    wsl_c NUMERIC(8,1),
    wcb_c NUMERIC(8,1),
    wch_c NUMERIC(8,1),
    wsf_c NUMERIC(8,1),
    
    -- Plate discipline
    o_swing_pct NUMERIC(6,2),
    z_swing_pct NUMERIC(6,2),
    swing_pct NUMERIC(6,2),
    o_contact_pct NUMERIC(6,2),
    z_contact_pct NUMERIC(6,2),
    contact_pct NUMERIC(6,2),
    zone_pct NUMERIC(6,2),
    f_strike_pct NUMERIC(6,2),
    swstr_pct NUMERIC(6,2),
    cstr_pct NUMERIC(6,2),
    c_swstr_pct NUMERIC(6,2),
    hld INTEGER,
    xfip2 NUMERIC(6,2),
    siera NUMERIC(6,2),
    rs_9 NUMERIC(6,2),
    
    -- Batted ball direction
    pull INTEGER,
    cent INTEGER,
    oppo INTEGER,
    soft INTEGER,
    med INTEGER,
    hard INTEGER,
    bipcount INTEGER,
    pull_pct NUMERIC(6,2),
    cent_pct NUMERIC(6,2),
    oppo_pct NUMERIC(6,2),
    soft_pct NUMERIC(6,2),
    med_pct NUMERIC(6,2),
    hard_pct NUMERIC(6,2),
    
    -- Duplicate columns
    ld_pct2 NUMERIC(6,2),
    gb_pct2 NUMERIC(6,2),
    fb_pct2 NUMERIC(6,2),
    hrfb_pct NUMERIC(6,2),
    pull_pct2 NUMERIC(6,2),
    cent_pct2 NUMERIC(6,2),
    oppo_pct2 NUMERIC(6,2),
    soft_pct2 NUMERIC(6,2),
    med_pct2 NUMERIC(6,2),
    hard_pct2 NUMERIC(6,2),
    
    -- Knuckleball
    kn_pct NUMERIC(6,2),
    knv NUMERIC(6,1),
    wkn NUMERIC(8,1),
    wkn_c NUMERIC(8,1),
    
    -- Cutter
    po_pct NUMERIC(6,2),
    ct_pct NUMERIC(6,2),
    ctv NUMERIC(6,1),
    wct NUMERIC(8,1),
    wct_c NUMERIC(8,1),
    dgv NUMERIC(8,1),
    
    -- PITCHf/x data (same structure as batting)
    pfx_fa_pct NUMERIC(6,2),
    pfx_fc_pct NUMERIC(6,2),
    pfx_sl_pct NUMERIC(6,2),
    pfx_cu_pct NUMERIC(6,2),
    pfx_ch_pct NUMERIC(6,2),
    pfx_vfa NUMERIC(6,1),
    pfx_vfc NUMERIC(6,1),
    pfx_vsl NUMERIC(6,1),
    pfx_vcu NUMERIC(6,1),
    pfx_vch NUMERIC(6,1),
    pfx_fa_x NUMERIC(6,2),
    pfx_fc_x NUMERIC(6,2),
    pfx_sl_x NUMERIC(6,2),
    pfx_cu_x NUMERIC(6,2),
    pfx_ch_x NUMERIC(6,2),
    pfx_fa_z NUMERIC(6,2),
    pfx_fc_z NUMERIC(6,2),
    pfx_sl_z NUMERIC(6,2),
    pfx_cu_z NUMERIC(6,2),
    pfx_ch_z NUMERIC(6,2),
    pfx_wfa NUMERIC(8,1),
    pfx_wfc NUMERIC(8,1),
    pfx_wsl NUMERIC(8,1),
    pfx_wcu NUMERIC(8,1),
    pfx_wch NUMERIC(8,1),
    pfx_wfa_c NUMERIC(8,1),
    pfx_wfc_c NUMERIC(8,1),
    pfx_wsl_c NUMERIC(8,1),
    pfx_wcu_c NUMERIC(8,1),
    pfx_wch_c NUMERIC(8,1),
    pfx_o_swing_pct NUMERIC(6,2),
    pfx_z_swing_pct NUMERIC(6,2),
    pfx_swing_pct NUMERIC(6,2),
    pfx_o_contact_pct NUMERIC(6,2),
    pfx_z_contact_pct NUMERIC(6,2),
    pfx_contact_pct NUMERIC(6,2),
    pfx_zone_pct NUMERIC(6,2),
    
    -- PITCHInfo data
    pi_ch_pct NUMERIC(6,2),
    pi_cu_pct NUMERIC(6,2),
    pi_fa_pct NUMERIC(6,2),
    pi_fc_pct NUMERIC(6,2),
    pi_fs_pct NUMERIC(6,2),
    pi_kn_pct NUMERIC(6,2),
    pi_si_pct NUMERIC(6,2),
    pi_sl_pct NUMERIC(6,2),
    pi_xx_pct NUMERIC(6,2),
    pi_vch NUMERIC(6,1),
    pi_vcu NUMERIC(6,1),
    pi_vfa NUMERIC(6,1),
    pi_vfc NUMERIC(6,1),
    pi_vfs NUMERIC(6,1),
    pi_vkn NUMERIC(6,1),
    pi_vsi NUMERIC(6,1),
    pi_vsl NUMERIC(6,1),
    pi_vxx NUMERIC(6,1),
    pi_ch_x NUMERIC(6,2),
    pi_cu_x NUMERIC(6,2),
    pi_fa_x NUMERIC(6,2),
    pi_fc_x NUMERIC(6,2),
    pi_fs_x NUMERIC(6,2),
    pi_kn_x NUMERIC(6,2),
    pi_si_x NUMERIC(6,2),
    pi_sl_x NUMERIC(6,2),
    pi_xx_x NUMERIC(6,2),
    pi_ch_z NUMERIC(6,2),
    pi_cu_z NUMERIC(6,2),
    pi_fa_z NUMERIC(6,2),
    pi_fc_z NUMERIC(6,2),
    pi_fs_z NUMERIC(6,2),
    pi_kn_z NUMERIC(6,2),
    pi_si_z NUMERIC(6,2),
    pi_sl_z NUMERIC(6,2),
    pi_xx_z NUMERIC(6,2),
    pi_wch NUMERIC(8,1),
    pi_wcu NUMERIC(8,1),
    pi_wfa NUMERIC(8,1),
    pi_wfc NUMERIC(8,1),
    pi_wfs NUMERIC(8,1),
    pi_wkn NUMERIC(8,1),
    pi_wsi NUMERIC(8,1),
    pi_wsl NUMERIC(8,1),
    pi_wxx NUMERIC(8,1),
    pi_wch_c NUMERIC(8,1),
    pi_wcu_c NUMERIC(8,1),
    pi_wfa_c NUMERIC(8,1),
    pi_wfc_c NUMERIC(8,1),
    pi_wfs_c NUMERIC(8,1),
    pi_wkn_c NUMERIC(8,1),
    pi_wsi_c NUMERIC(8,1),
    pi_wsl_c NUMERIC(8,1),
    pi_wxx_c NUMERIC(8,1),
    pi_o_swing_pct NUMERIC(6,2),
    pi_z_swing_pct NUMERIC(6,2),
    pi_swing_pct NUMERIC(6,2),
    pi_o_contact_pct NUMERIC(6,2),
    pi_z_contact_pct NUMERIC(6,2),
    pi_contact_pct NUMERIC(6,2),
    pi_zone_pct NUMERIC(6,2),
    
    -- StatCast
    barrels INTEGER,
    hardhit INTEGER,
    
    -- More PITCHf/x
    pfx_si_pct NUMERIC(6,2),
    pfx_vsi NUMERIC(6,1),
    pfx_si_x NUMERIC(6,2),
    pfx_si_z NUMERIC(6,2),
    pfx_wsi NUMERIC(8,1),
    pfx_wsi_c NUMERIC(8,1),
    pfx_fs_pct NUMERIC(6,2),
    pfx_vfs NUMERIC(6,1),
    pfx_fs_x NUMERIC(6,2),
    pfx_fs_z NUMERIC(6,2),
    pfx_wfs NUMERIC(8,1),
    pfx_wfs_c NUMERIC(8,1),
    
    -- Stolen bases
    pi_cs_pct NUMERIC(6,2),
    pi_vcs NUMERIC(6,1),
    pi_cs_x NUMERIC(6,2),
    pi_cs_z NUMERIC(6,2),
    pi_wcs NUMERIC(8,1),
    pi_wcs_c NUMERIC(8,1),
    pfx_kn_pct NUMERIC(6,2),
    pfx_vkn NUMERIC(6,1),
    pfx_kn_x NUMERIC(6,2),
    pfx_kn_z NUMERIC(6,2),
    pfx_wkn NUMERIC(8,1),
    pfx_wkn_c NUMERIC(8,1),
    pi_sb_pct NUMERIC(6,2),
    pi_vsb NUMERIC(6,1),
    pi_sb_x NUMERIC(6,2),
    pi_sb_z NUMERIC(6,2),
    pi_wsb NUMERIC(8,1),
    pi_wsb_c NUMERIC(8,1),
    
    -- Catcher framing
    cframing NUMERIC(8,1),
    
    -- More PITCHf/x pitch types
    pfx_kc_pct NUMERIC(6,2),
    pfx_vkc NUMERIC(6,1),
    pfx_kc_x NUMERIC(6,2),
    pfx_kc_z NUMERIC(6,2),
    pfx_wkc NUMERIC(8,1),
    pfx_wkc_c NUMERIC(8,1),
    pfx_ep_pct NUMERIC(6,2),
    pfx_vep NUMERIC(6,1),
    pfx_ep_x NUMERIC(6,2),
    pfx_ep_z NUMERIC(6,2),
    pfx_wep NUMERIC(8,1),
    pfx_wep_c NUMERIC(8,1),
    pfx_fo_pct NUMERIC(6,2),
    pfx_vfo NUMERIC(6,1),
    pfx_fo_x NUMERIC(6,2),
    pfx_fo_z NUMERIC(6,2),
    pfx_wfo NUMERIC(8,1),
    pfx_wfo_c NUMERIC(8,1),
    pfx_sc_pct NUMERIC(6,2),
    pfx_vsc NUMERIC(6,1),
    pfx_sc_x NUMERIC(6,2),
    pfx_sc_z NUMERIC(6,2),
    pfx_wsc NUMERIC(8,1),
    pfx_wsc_c NUMERIC(8,1),
    pfx_pace NUMERIC(6,2),
    pi_pace NUMERIC(6,2),
    
    -- Expected stats
    xera NUMERIC(6,2),
    
    -- StatCast metrics
    ev NUMERIC(6,1),
    la NUMERIC(6,1),
    barrel_pct NUMERIC(6,2),
    maxev NUMERIC(6,1),
    hardhit_pct NUMERIC(6,2),
    ev90 NUMERIC(6,1),
    
    -- PitchBot metrics
    pb_o_ch NUMERIC(6,1),
    pb_s_ch NUMERIC(6,1),
    pb_c_ch NUMERIC(6,1),
    pb_o_ff NUMERIC(6,1),
    pb_s_ff NUMERIC(6,1),
    pb_c_ff NUMERIC(6,1),
    pb_o_sl NUMERIC(6,1),
    pb_s_sl NUMERIC(6,1),
    pb_c_sl NUMERIC(6,1),
    pb_o_kc NUMERIC(6,1),
    pb_s_kc NUMERIC(6,1),
    pb_c_kc NUMERIC(6,1),
    pb_o_fc NUMERIC(6,1),
    pb_s_fc NUMERIC(6,1),
    pb_c_fc NUMERIC(6,1),
    pb_overall NUMERIC(6,1),
    pb_stuff NUMERIC(6,1),
    pb_command NUMERIC(6,1),
    pb_xrv100 NUMERIC(6,1),
    pb_era NUMERIC(6,2),
    
    -- Stuff+ metrics
    sp_s_ch NUMERIC(6,1),
    sp_l_ch NUMERIC(6,1),
    sp_p_ch NUMERIC(6,1),
    sp_s_ff NUMERIC(6,1),
    sp_l_ff NUMERIC(6,1),
    sp_p_ff NUMERIC(6,1),
    sp_s_sl NUMERIC(6,1),
    sp_l_sl NUMERIC(6,1),
    sp_p_sl NUMERIC(6,1),
    sp_s_kc NUMERIC(6,1),
    sp_l_kc NUMERIC(6,1),
    sp_p_kc NUMERIC(6,1),
    sp_s_fc NUMERIC(6,1),
    sp_l_fc NUMERIC(6,1),
    sp_p_fc NUMERIC(6,1),
    sp_stuff NUMERIC(6,1),
    sp_location NUMERIC(6,1),
    sp_pitching NUMERIC(6,1),
    
    -- More PitchBot
    pb_o_cu NUMERIC(6,1),
    pb_s_cu NUMERIC(6,1),
    pb_c_cu NUMERIC(6,1),
    pb_o_si NUMERIC(6,1),
    pb_s_si NUMERIC(6,1),
    pb_c_si NUMERIC(6,1),
    pb_o_fs NUMERIC(6,1),
    pb_s_fs NUMERIC(6,1),
    pb_c_fs NUMERIC(6,1),
    
    -- More Stuff+
    sp_s_cu NUMERIC(6,1),
    sp_l_cu NUMERIC(6,1),
    sp_p_cu NUMERIC(6,1),
    sp_s_si NUMERIC(6,1),
    sp_l_si NUMERIC(6,1),
    sp_p_si NUMERIC(6,1),
    sp_s_fs NUMERIC(6,1),
    sp_l_fs NUMERIC(6,1),
    sp_p_fs NUMERIC(6,1),
    
    -- Team value metrics
    pptv NUMERIC(8,1),
    cptv NUMERIC(8,1),
    bptv NUMERIC(8,1),
    dsv NUMERIC(8,1),
    btv NUMERIC(8,1),
    rpptv NUMERIC(8,1),
    rbptv NUMERIC(8,1),
    ebv NUMERIC(8,1),
    esv NUMERIC(8,1),
    rbtv NUMERIC(8,1),
    rcptv NUMERIC(8,1),
    sp_s_fo NUMERIC(6,1),
    sp_l_fo NUMERIC(6,1),
    sp_p_fo NUMERIC(6,1),
    rdgv NUMERIC(8,1),
    rdsv NUMERIC(8,1),
    
    -- Import metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (playerid, season)
);

-- ============================================================================
-- FANGRAPHS FIELDING LEADERS (Exact column match)
-- ============================================================================

CREATE TABLE IF NOT EXISTS fg_fielding_raw (
    -- Core identifiers
    season INTEGER,
    team_name VARCHAR(100),
    xmlbamid INTEGER,
    playernameroute VARCHAR(255),
    playername VARCHAR(255),
    playerid INTEGER,
    seasonmin INTEGER,
    seasonmax INTEGER,
    
    -- Position and games
    pos VARCHAR(10),
    g INTEGER,
    po INTEGER,
    a INTEGER,
    e INTEGER,
    dp INTEGER,
    fp NUMERIC(6,3),
    tz INTEGER,
    q NUMERIC(6,1),
    tinn NUMERIC(8,1),
    teamid INTEGER,
    team_name_abb VARCHAR(10),
    
    -- Catcher specific
    pb INTEGER,
    gs INTEGER,
    inn NUMERIC(8,1),
    sb INTEGER,
    wp INTEGER,
    cs INTEGER,
    fe INTEGER,
    te INTEGER,
    dps INTEGER,
    dpt INTEGER,
    dpf INTEGER,
    rgdp INTEGER,
    rgfp INTEGER,
    rpm INTEGER,
    
    -- Advanced fielding metrics
    drs INTEGER,
    biz INTEGER,
    plays INTEGER,
    ooz INTEGER,
    dpr NUMERIC(8,1),
    rngr NUMERIC(8,1),
    errr NUMERIC(8,1),
    uzr NUMERIC(8,1),
    uzr_150 NUMERIC(8,1),
    defense NUMERIC(8,1),
    rarm NUMERIC(8,1),
    arm NUMERIC(8,1),
    rsb NUMERIC(8,1),
    rsz NUMERIC(8,1),
    rcera NUMERIC(8,1),
    scp INTEGER,
    rzr NUMERIC(6,3),
    cpp NUMERIC(6,3),
    rpp NUMERIC(6,3),
    cstrikes INTEGER,
    cframing NUMERIC(8,1),
    fsr NUMERIC(6,3),
    
    -- Probability-based metrics
    prob0 NUMERIC(6,3),
    made10 INTEGER,
    prob10 NUMERIC(6,3),
    made40 INTEGER,
    prob40 NUMERIC(6,3),
    made60 INTEGER,
    prob60 NUMERIC(6,3),
    made90 INTEGER,
    prob90 NUMERIC(6,3),
    made100 INTEGER,
    prob100 NUMERIC(6,3),
    made0 INTEGER,
    
    -- Framing metrics
    dfrp NUMERIC(8,1),
    bfrp NUMERIC(8,1),
    tfrp NUMERIC(8,1),
    ffrp NUMERIC(8,1),
    frp NUMERIC(8,1),
    oaa NUMERIC(8,1),
    rfrp NUMERIC(8,1),
    afrp NUMERIC(8,1),
    
    -- Import metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (playerid, season, pos)
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Batting indexes
CREATE INDEX IF NOT EXISTS idx_fg_batting_season ON fg_batting_raw(season);
CREATE INDEX IF NOT EXISTS idx_fg_batting_player ON fg_batting_raw(playerid);
CREATE INDEX IF NOT EXISTS idx_fg_batting_war ON fg_batting_raw(war DESC);
CREATE INDEX IF NOT EXISTS idx_fg_batting_wrc_plus ON fg_batting_raw(wrc_plus DESC);
CREATE INDEX IF NOT EXISTS idx_fg_batting_team ON fg_batting_raw(team_name_abb);

-- Pitching indexes
CREATE INDEX IF NOT EXISTS idx_fg_pitching_season ON fg_pitching_raw(season);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_player ON fg_pitching_raw(playerid);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_war ON fg_pitching_raw(war DESC);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_era ON fg_pitching_raw(era);

-- Fielding indexes
CREATE INDEX IF NOT EXISTS idx_fg_fielding_season ON fg_fielding_raw(season);
CREATE INDEX IF NOT EXISTS idx_fg_fielding_player ON fg_fielding_raw(playerid);
CREATE INDEX IF NOT EXISTS idx_fg_fielding_pos ON fg_fielding_raw(pos);
CREATE INDEX IF NOT EXISTS idx_fg_fielding_uzr ON fg_fielding_raw(uzr DESC);
CREATE INDEX IF NOT EXISTS idx_fg_fielding_drs ON fg_fielding_raw(drs DESC);

COMMENT ON TABLE fg_batting_raw IS 'FanGraphs batting leaders - exact column match to ETL output';
COMMENT ON TABLE fg_pitching_raw IS 'FanGraphs pitching leaders - exact column match to ETL output';
COMMENT ON TABLE fg_fielding_raw IS 'FanGraphs fielding leaders - exact column match to ETL output';