-- FanGraphs Pitching Schema (Clean Column Names)

CREATE TABLE IF NOT EXISTS fg_pitching_leaders (
    -- Core identifiers
    season INTEGER NOT NULL,
    team_name TEXT,
    throws TEXT,
    x_mlbamid INTEGER,
    player_name_route TEXT,
    player_name TEXT,
    playerid INTEGER NOT NULL,
    age INTEGER,
    age_rng TEXT,
    season_min INTEGER,
    season_max INTEGER,
    
    -- Basic pitching stats
    w INTEGER,
    l INTEGER,
    era NUMERIC(6,2),
    g INTEGER,
    gs INTEGER,
    cg INTEGER,
    sh_o INTEGER,
    sv INTEGER,
    hld INTEGER,
    bs INTEGER,
    ip NUMERIC(8,1),
    h INTEGER,
    r INTEGER,
    er INTEGER,
    hr INTEGER,
    bb INTEGER,
    ibb INTEGER,
    hbp INTEGER,
    wp INTEGER,
    bk INTEGER,
    so INTEGER,
    tbf INTEGER,
    
    -- Rate stats
    k_9 NUMERIC(6,2),
    bb_9 NUMERIC(6,2),
    k_bb NUMERIC(6,3),
    h_9 NUMERIC(6,2),
    hr_9 NUMERIC(6,2),
    batting_avg NUMERIC(6,3),
    whip NUMERIC(6,3),
    babip NUMERIC(6,3),
    lob_pct NUMERIC(6,2),
    fip NUMERIC(6,2),
    x_fip NUMERIC(6,2),
    t_era NUMERIC(6,2),
    siera NUMERIC(6,2),
    
    -- Advanced metrics
    rar NUMERIC(8,1),
    war NUMERIC(6,1),
    ra9_wins NUMERIC(6,1),
    lob_wins NUMERIC(6,1),
    bip_wins NUMERIC(6,1),
    bs_wins NUMERIC(6,1),
    games NUMERIC(6,1),
    era_minus INTEGER,
    fip_minus INTEGER,
    x_fip_minus INTEGER,
    kw_era NUMERIC(6,2),
    e_f NUMERIC(6,2),
    
    -- Plus stats (era-adjusted)
    k_9_plus INTEGER,
    bb_9_plus INTEGER,
    k_bb_plus INTEGER,
    h_9_plus INTEGER,
    hr_9_plus INTEGER,
    avg_plus INTEGER,
    whip_plus INTEGER,
    babip_plus INTEGER,
    lob_pct_plus INTEGER,
    
    -- Team value stats
    r_fteam_v NUMERIC(8,1),
    r_bteam_v NUMERIC(8,1),
    r_tv NUMERIC(8,1),
    events INTEGER,
    q NUMERIC(6,1),
    tg NUMERIC(6,1),
    tip NUMERIC(8,1),
    
    -- Team info
    pos TEXT,
    team_name_abb TEXT,
    teamid INTEGER,
    
    -- Plate discipline
    tto_pct NUMERIC(6,2),
    k_pct NUMERIC(6,2),
    bb_pct NUMERIC(6,2),
    k_minus_bb_pct NUMERIC(6,2),
    k_pct_plus INTEGER,
    bb_pct_plus INTEGER,
    
    -- Game situation
    qs INTEGER,
    starting NUMERIC(6,1),
    start_ip NUMERIC(8,1),
    relieving NUMERIC(6,1),
    relief_ip NUMERIC(8,1),
    rs INTEGER,
    rs_9 NUMERIC(6,2),
    
    -- Win probability
    wpa NUMERIC(8,2),
    wpa_minus NUMERIC(8,2),
    wpa_plus NUMERIC(8,2),
    re24 NUMERIC(8,1),
    rew NUMERIC(8,1),
    p_li NUMERIC(6,2),
    in_li NUMERIC(6,2),
    gm_li NUMERIC(6,2),
    ex_li NUMERIC(6,2),
    pulls INTEGER,
    wpa_li NUMERIC(8,2),
    clutch NUMERIC(8,2),
    sd INTEGER,
    md INTEGER,
    
    -- Batted ball data
    gb INTEGER,
    fb INTEGER,
    ld INTEGER,
    iffb INTEGER,
    pitches INTEGER,
    balls INTEGER,
    strikes INTEGER,
    ifh INTEGER,
    bu INTEGER,
    buh INTEGER,
    gb_fb NUMERIC(6,3),
    ld_pct NUMERIC(6,2),
    gb_pct NUMERIC(6,2),
    fb_pct NUMERIC(6,2),
    iffb_pct NUMERIC(6,2),
    hr_fb NUMERIC(6,2),
    ifh_pct NUMERIC(6,2),
    buh_pct NUMERIC(6,2),
    dollars NUMERIC(10,1),
    
    -- Pitch type percentages
    fb_pct1 NUMERIC(6,2),
    fbv NUMERIC(6,1),
    sl_pct NUMERIC(6,2),
    slv NUMERIC(6,1),
    cb_pct NUMERIC(6,2),
    cbv NUMERIC(6,1),
    ch_pct NUMERIC(6,2),
    chv NUMERIC(6,1),
    sf_pct NUMERIC(6,2),
    sfv NUMERIC(6,1),
    xx_pct NUMERIC(6,2),
    kn_pct NUMERIC(6,2),
    knv NUMERIC(6,1),
    po_pct NUMERIC(6,2),
    ct_pct NUMERIC(6,2),
    ctv NUMERIC(6,1),
    
    -- Pitch values
    w_fb NUMERIC(8,1),
    w_sl NUMERIC(8,1),
    w_cb NUMERIC(8,1),
    w_ch NUMERIC(8,1),
    w_sf NUMERIC(8,1),
    w_fb_c NUMERIC(8,1),
    w_sl_c NUMERIC(8,1),
    w_cb_c NUMERIC(8,1),
    w_ch_c NUMERIC(8,1),
    w_sf_c NUMERIC(8,1),
    w_kn NUMERIC(8,1),
    w_kn_c NUMERIC(8,1),
    w_ct NUMERIC(8,1),
    w_ct_c NUMERIC(8,1),
    
    -- Plate discipline (pitcher)
    o_swing_pct NUMERIC(6,2),
    z_swing_pct NUMERIC(6,2),
    swing_pct NUMERIC(6,2),
    o_contact_pct NUMERIC(6,2),
    z_contact_pct NUMERIC(6,2),
    contact_pct NUMERIC(6,2),
    zone_pct NUMERIC(6,2),
    f_strike_pct NUMERIC(6,2),
    sw_str_pct NUMERIC(6,2),
    cstr_pct NUMERIC(6,2),
    c_plus_sw_str_pct NUMERIC(6,2),
    
    -- Batted ball direction
    pull INTEGER,
    cent INTEGER,
    oppo INTEGER,
    soft INTEGER,
    med INTEGER,
    hard INTEGER,
    bip_count INTEGER,
    pull_pct NUMERIC(6,2),
    cent_pct NUMERIC(6,2),
    oppo_pct NUMERIC(6,2),
    soft_pct NUMERIC(6,2),
    med_pct NUMERIC(6,2),
    hard_pct NUMERIC(6,2),
    
    -- Plus stats (batted ball)
    ld_pct_plus INTEGER,
    gb_pct_plus INTEGER,
    fb_pct_plus INTEGER,
    hrfb_pct_plus INTEGER,
    pull_pct_plus INTEGER,
    cent_pct_plus INTEGER,
    oppo_pct_plus INTEGER,
    soft_pct_plus INTEGER,
    med_pct_plus INTEGER,
    hard_pct_plus INTEGER,
    
    -- PITCHf/x data
    pfx_fa_pct NUMERIC(6,2),
    pfx_fc_pct NUMERIC(6,2),
    pfx_sl_pct NUMERIC(6,2),
    pfx_cu_pct NUMERIC(6,2),
    pfx_ch_pct NUMERIC(6,2),
    pfx_si_pct NUMERIC(6,2),
    pfx_fs_pct NUMERIC(6,2),
    pfx_kn_pct NUMERIC(6,2),
    pfx_kc_pct NUMERIC(6,2),
    pfx_ep_pct NUMERIC(6,2),
    pfx_fo_pct NUMERIC(6,2),
    pfx_sc_pct NUMERIC(6,2),
    pfx_v_fa NUMERIC(6,1),
    pfx_v_fc NUMERIC(6,1),
    pfx_v_sl NUMERIC(6,1),
    pfx_v_cu NUMERIC(6,1),
    pfx_v_ch NUMERIC(6,1),
    pfx_v_si NUMERIC(6,1),
    pfx_v_fs NUMERIC(6,1),
    pfx_v_kn NUMERIC(6,1),
    pfx_v_kc NUMERIC(6,1),
    pfx_v_ep NUMERIC(6,1),
    pfx_v_fo NUMERIC(6,1),
    pfx_v_sc NUMERIC(6,1),
    pfx_fa_x NUMERIC(6,2),
    pfx_fc_x NUMERIC(6,2),
    pfx_sl_x NUMERIC(6,2),
    pfx_cu_x NUMERIC(6,2),
    pfx_ch_x NUMERIC(6,2),
    pfx_si_x NUMERIC(6,2),
    pfx_fs_x NUMERIC(6,2),
    pfx_kn_x NUMERIC(6,2),
    pfx_kc_x NUMERIC(6,2),
    pfx_ep_x NUMERIC(6,2),
    pfx_fo_x NUMERIC(6,2),
    pfx_sc_x NUMERIC(6,2),
    pfx_fa_z NUMERIC(6,2),
    pfx_fc_z NUMERIC(6,2),
    pfx_sl_z NUMERIC(6,2),
    pfx_cu_z NUMERIC(6,2),
    pfx_ch_z NUMERIC(6,2),
    pfx_si_z NUMERIC(6,2),
    pfx_fs_z NUMERIC(6,2),
    pfx_kn_z NUMERIC(6,2),
    pfx_kc_z NUMERIC(6,2),
    pfx_ep_z NUMERIC(6,2),
    pfx_fo_z NUMERIC(6,2),
    pfx_sc_z NUMERIC(6,2),
    pfx_w_fa NUMERIC(8,1),
    pfx_w_fc NUMERIC(8,1),
    pfx_w_sl NUMERIC(8,1),
    pfx_w_cu NUMERIC(8,1),
    pfx_w_ch NUMERIC(8,1),
    pfx_w_si NUMERIC(8,1),
    pfx_w_fs NUMERIC(8,1),
    pfx_w_kn NUMERIC(8,1),
    pfx_w_kc NUMERIC(8,1),
    pfx_w_ep NUMERIC(8,1),
    pfx_w_fo NUMERIC(8,1),
    pfx_w_sc NUMERIC(8,1),
    pfx_w_fa_c NUMERIC(8,1),
    pfx_w_fc_c NUMERIC(8,1),
    pfx_w_sl_c NUMERIC(8,1),
    pfx_w_cu_c NUMERIC(8,1),
    pfx_w_ch_c NUMERIC(8,1),
    pfx_w_si_c NUMERIC(8,1),
    pfx_w_fs_c NUMERIC(8,1),
    pfx_w_kn_c NUMERIC(8,1),
    pfx_w_kc_c NUMERIC(8,1),
    pfx_w_ep_c NUMERIC(8,1),
    pfx_w_fo_c NUMERIC(8,1),
    pfx_w_sc_c NUMERIC(8,1),
    pfx_o_swing_pct NUMERIC(6,2),
    pfx_z_swing_pct NUMERIC(6,2),
    pfx_swing_pct NUMERIC(6,2),
    pfx_o_contact_pct NUMERIC(6,2),
    pfx_z_contact_pct NUMERIC(6,2),
    pfx_contact_pct NUMERIC(6,2),
    pfx_zone_pct NUMERIC(6,2),
    pfx_pace NUMERIC(6,2),
    
    -- PITCHInfo data
    pi_ch_pct NUMERIC(6,2),
    pi_cu_pct NUMERIC(6,2),
    pi_fa_pct NUMERIC(6,2),
    pi_fc_pct NUMERIC(6,2),
    pi_fs_pct NUMERIC(6,2),
    pi_kn_pct NUMERIC(6,2),
    pi_si_pct NUMERIC(6,2),
    pi_sl_pct NUMERIC(6,2),
    pi_xx_pct NUMERIC(6,2),
    pi_cs_pct NUMERIC(6,2),
    pi_sb_pct NUMERIC(6,2),
    pi_v_ch NUMERIC(6,1),
    pi_v_cu NUMERIC(6,1),
    pi_v_fa NUMERIC(6,1),
    pi_v_fc NUMERIC(6,1),
    pi_v_fs NUMERIC(6,1),
    pi_v_kn NUMERIC(6,1),
    pi_v_si NUMERIC(6,1),
    pi_v_sl NUMERIC(6,1),
    pi_v_xx NUMERIC(6,1),
    pi_v_cs NUMERIC(6,1),
    pi_v_sb NUMERIC(6,1),
    pi_ch_x NUMERIC(6,2),
    pi_cu_x NUMERIC(6,2),
    pi_fa_x NUMERIC(6,2),
    pi_fc_x NUMERIC(6,2),
    pi_fs_x NUMERIC(6,2),
    pi_kn_x NUMERIC(6,2),
    pi_si_x NUMERIC(6,2),
    pi_sl_x NUMERIC(6,2),
    pi_xx_x NUMERIC(6,2),
    pi_cs_x NUMERIC(6,2),
    pi_sb_x NUMERIC(6,2),
    pi_ch_z NUMERIC(6,2),
    pi_cu_z NUMERIC(6,2),
    pi_fa_z NUMERIC(6,2),
    pi_fc_z NUMERIC(6,2),
    pi_fs_z NUMERIC(6,2),
    pi_kn_z NUMERIC(6,2),
    pi_si_z NUMERIC(6,2),
    pi_sl_z NUMERIC(6,2),
    pi_xx_z NUMERIC(6,2),
    pi_cs_z NUMERIC(6,2),
    pi_sb_z NUMERIC(6,2),
    pi_w_ch NUMERIC(8,1),
    pi_w_cu NUMERIC(8,1),
    pi_w_fa NUMERIC(8,1),
    pi_w_fc NUMERIC(8,1),
    pi_w_fs NUMERIC(8,1),
    pi_w_kn NUMERIC(8,1),
    pi_w_si NUMERIC(8,1),
    pi_w_sl NUMERIC(8,1),
    pi_w_xx NUMERIC(8,1),
    pi_w_cs NUMERIC(8,1),
    pi_w_sb NUMERIC(8,1),
    pi_w_ch_c NUMERIC(8,1),
    pi_w_cu_c NUMERIC(8,1),
    pi_w_fa_c NUMERIC(8,1),
    pi_w_fc_c NUMERIC(8,1),
    pi_w_fs_c NUMERIC(8,1),
    pi_w_kn_c NUMERIC(8,1),
    pi_w_si_c NUMERIC(8,1),
    pi_w_sl_c NUMERIC(8,1),
    pi_w_xx_c NUMERIC(8,1),
    pi_w_cs_c NUMERIC(8,1),
    pi_w_sb_c NUMERIC(8,1),
    pi_o_swing_pct NUMERIC(6,2),
    pi_z_swing_pct NUMERIC(6,2),
    pi_swing_pct NUMERIC(6,2),
    pi_o_contact_pct NUMERIC(6,2),
    pi_z_contact_pct NUMERIC(6,2),
    pi_contact_pct NUMERIC(6,2),
    pi_zone_pct NUMERIC(6,2),
    pi_pace NUMERIC(6,2),
    
    -- StatCast metrics
    barrels INTEGER,
    hard_hit INTEGER,
    ev NUMERIC(6,1),
    la NUMERIC(6,1),
    barrel_pct NUMERIC(6,2),
    max_ev NUMERIC(6,1),
    hard_hit_pct NUMERIC(6,2),
    ev90 NUMERIC(6,1),
    
    -- Expected stats
    x_era NUMERIC(6,2),
    
    -- Catcher framing
    cframing NUMERIC(8,1),
    
    -- PitchBot metrics
    pb_o_ch NUMERIC(6,1),
    pb_s_ch NUMERIC(6,1),
    pb_c_ch NUMERIC(6,1),
    pb_o_ff NUMERIC(6,1),
    pb_s_ff NUMERIC(6,1),
    pb_c_ff NUMERIC(6,1),
    pb_o_sl NUMERIC(6,1),
    pb_s_sl NUMERIC(6,1),
    pb_c_sl NUMERIC(6,1),
    pb_o_kc NUMERIC(6,1),
    pb_s_kc NUMERIC(6,1),
    pb_c_kc NUMERIC(6,1),
    pb_o_fc NUMERIC(6,1),
    pb_s_fc NUMERIC(6,1),
    pb_c_fc NUMERIC(6,1),
    pb_o_cu NUMERIC(6,1),
    pb_s_cu NUMERIC(6,1),
    pb_c_cu NUMERIC(6,1),
    pb_o_si NUMERIC(6,1),
    pb_s_si NUMERIC(6,1),
    pb_c_si NUMERIC(6,1),
    pb_o_fs NUMERIC(6,1),
    pb_s_fs NUMERIC(6,1),
    pb_c_fs NUMERIC(6,1),
    pb_overall NUMERIC(6,1),
    pb_stuff NUMERIC(6,1),
    pb_command NUMERIC(6,1),
    pb_x_rv100 NUMERIC(6,1),
    pb_era NUMERIC(6,2),
    
    -- Stuff+ metrics
    sp_s_ch NUMERIC(6,1),
    sp_l_ch NUMERIC(6,1),
    sp_p_ch NUMERIC(6,1),
    sp_s_ff NUMERIC(6,1),
    sp_l_ff NUMERIC(6,1),
    sp_p_ff NUMERIC(6,1),
    sp_s_sl NUMERIC(6,1),
    sp_l_sl NUMERIC(6,1),
    sp_p_sl NUMERIC(6,1),
    sp_s_kc NUMERIC(6,1),
    sp_l_kc NUMERIC(6,1),
    sp_p_kc NUMERIC(6,1),
    sp_s_fc NUMERIC(6,1),
    sp_l_fc NUMERIC(6,1),
    sp_p_fc NUMERIC(6,1),
    sp_s_cu NUMERIC(6,1),
    sp_l_cu NUMERIC(6,1),
    sp_p_cu NUMERIC(6,1),
    sp_s_si NUMERIC(6,1),
    sp_l_si NUMERIC(6,1),
    sp_p_si NUMERIC(6,1),
    sp_s_fs NUMERIC(6,1),
    sp_l_fs NUMERIC(6,1),
    sp_p_fs NUMERIC(6,1),
    sp_s_fo NUMERIC(6,1),
    sp_l_fo NUMERIC(6,1),
    sp_p_fo NUMERIC(6,1),
    sp_stuff NUMERIC(6,1),
    sp_location NUMERIC(6,1),
    sp_pitching NUMERIC(6,1),
    
    -- Team value metrics
    pptv NUMERIC(8,1),
    cptv NUMERIC(8,1),
    bptv NUMERIC(8,1),
    dsv NUMERIC(8,1),
    btv NUMERIC(8,1),
    r_pptv NUMERIC(8,1),
    r_bptv NUMERIC(8,1),
    ebv NUMERIC(8,1),
    esv NUMERIC(8,1),
    r_btv NUMERIC(8,1),
    r_cptv NUMERIC(8,1),
    r_dgv NUMERIC(8,1),
    r_dsv NUMERIC(8,1),
    dgv NUMERIC(8,1),
    
    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Primary key
    CONSTRAINT fg_pitching_leaders_pkey PRIMARY KEY (playerid, season)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_fg_pitching_leaders_season ON fg_pitching_leaders(season);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_leaders_player ON fg_pitching_leaders(playerid);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_leaders_war ON fg_pitching_leaders(war DESC);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_leaders_era ON fg_pitching_leaders(era);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_leaders_fip ON fg_pitching_leaders(fip);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_leaders_team ON fg_pitching_leaders(team_name_abb);
CREATE INDEX IF NOT EXISTS idx_fg_pitching_leaders_player_name ON fg_pitching_leaders(player_name);

COMMENT ON TABLE fg_pitching_leaders IS 'FanGraphs pitching data with clean snake_case column names';